import type { FoodItem, MealPlan, Member, Category } from "../@types/types";

export const ITEMS_INIT: FoodItem[] = [
  {
    id: 1,
    name: "닭가슴살",
    cat: "육류",
    loc: "냉동",
    zone: "상단",
    bought: "2026-02-20",
    expiry: "2026-03-07",
    qty: 3,
    unit: "개",
    consumed: false,
  },
  {
    id: 2,
    name: "우유",
    cat: "유제품",
    loc: "냉장",
    zone: "도어",
    bought: "2026-03-01",
    expiry: "2026-03-06",
    qty: 1,
    unit: "개",
    consumed: false,
  },
  {
    id: 3,
    name: "달걀",
    cat: "유제품",
    loc: "냉장",
    zone: "도어",
    bought: "2026-02-25",
    expiry: "2026-03-25",
    qty: 10,
    unit: "개",
    consumed: false,
  },
  {
    id: 4,
    name: "시금치",
    cat: "채소",
    loc: "냉장",
    zone: "야채",
    bought: "2026-03-02",
    expiry: "2026-03-04",
    qty: 1,
    unit: "묶음",
    consumed: false,
  },
  {
    id: 5,
    name: "된장",
    cat: "양념",
    loc: "냉장",
    zone: "도어",
    bought: "2026-01-10",
    expiry: "2026-07-10",
    qty: 1,
    unit: "통",
    consumed: false,
  },
  {
    id: 6,
    name: "냉동만두",
    cat: "가공",
    loc: "냉동",
    zone: "하단",
    bought: "2026-02-15",
    expiry: "2026-05-15",
    qty: 2,
    unit: "봉",
    consumed: false,
  },
  {
    id: 7,
    name: "두부",
    cat: "두부",
    loc: "냉장",
    zone: "중단",
    bought: "2026-03-01",
    expiry: "2026-03-05",
    qty: 1,
    unit: "모",
    consumed: false,
  },
  {
    id: 8,
    name: "삼겹살",
    cat: "육류",
    loc: "냉동",
    zone: "중단",
    bought: "2026-02-28",
    expiry: "2026-04-28",
    qty: 2,
    unit: "팩",
    consumed: false,
  },
  {
    id: 9,
    name: "당근",
    cat: "채소",
    loc: "냉장",
    zone: "야채",
    bought: "2026-03-01",
    expiry: "2026-03-20",
    qty: 3,
    unit: "개",
    consumed: false,
  },
  {
    id: 10,
    name: "요거트",
    cat: "유제품",
    loc: "냉장",
    zone: "상단",
    bought: "2026-03-02",
    expiry: "2026-03-12",
    qty: 2,
    unit: "개",
    consumed: false,
  },
];

export const MEAL_PLAN: Record<string, MealPlan> = {
  월: { b: "달걀 스크램블", l: "시금치 된장국", d: "닭가슴살 샐러드" },
  화: { b: "요거트 볼", l: "두부 조림", d: "냉동만두 전골" },
  수: { b: "달걀 후라이", l: "된장찌개", d: "삼겹살 구이" },
  목: { b: "우유 시리얼", l: "닭가슴살 볶음밥", d: "두부 찌개" },
  금: { b: "달걀 찜", l: "당근 라페 샌드", d: "삼겹살 시금치" },
  토: { b: "브런치 에그", l: "된장찌개", d: "치킨 스테이크" },
  일: { b: "요거트 파르페", l: "만두 국", d: "삼겹살 파티" },
};

export const MEMBERS: Member[] = [
  {
    id: 1,
    name: "heejung",
    email: "heejung@email.com",
    role: "owner",
    color: "#10b981",
  },
  {
    id: 2,
    name: "지민",
    email: "jimin@email.com",
    role: "editor",
    color: "#3b82f6",
  },
  {
    id: 3,
    name: "수현",
    email: "suhyun@email.com",
    role: "viewer",
    color: "#f59e0b",
  },
];

export const CAT_COLORS: Record<Category, string> = {
  육류: "bg-red-100 text-red-500",
  채소: "bg-green-100 text-green-600",
  유제품: "bg-blue-100 text-blue-500",
  양념: "bg-yellow-100 text-yellow-600",
  가공: "bg-purple-100 text-purple-500",
  두부: "bg-orange-100 text-orange-500",
  기타: "bg-stone-100 text-stone-500",
};

export const CAT_DOT: Record<Category, string> = {
  육류: "bg-red-400",
  채소: "bg-green-400",
  유제품: "bg-blue-400",
  양념: "bg-yellow-400",
  가공: "bg-purple-400",
  두부: "bg-orange-400",
  기타: "bg-stone-400",
};

export const ZONES_냉장 = ["상단", "중단", "하단", "야채", "도어"] as const;
export const ZONES_냉동 = ["상단", "중단", "하단"] as const;
export const CATEGORIES: Category[] = [
  "채소",
  "육류",
  "유제품",
  "양념",
  "가공",
  "두부",
  "기타",
];
export const ROLE_META = {
  owner: { label: "소유자", cls: "bg-emerald-100 text-emerald-700" },
  editor: { label: "편집자", cls: "bg-blue-100 text-blue-700" },
  viewer: { label: "열람자", cls: "bg-amber-100 text-amber-700" },
};
export const TODAY = new Date("2026-03-03");
